version: "3.9"
services:
  server:
    image: "abhishekcoder/sample_trading_data_model:server"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
      - price_producer
    build: .
    ports:
      - "127.0.0.1:5555:5555"
      
  price_producer:
    image: "abhishekcoder/sample_trading_data_model:price_producer"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
    restart: always

  deaggregator:
    image: "abhishekcoder/sample_trading_data_model:deaggregator"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
      - price_producer

  redis:
    image: "redis/redis-stack:latest"
    env_file:
      - docker-compose-redis-variables.env
    command: /bin/sh -c "redis-stack-server --requirepass $$PASSWORD"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: