version: "3.9"
networks:
  portfolio-app:
    driver: bridge
services:
  server:
    image: "abhishekcoder/securities_portfolio_app:server"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
      - price_producer
      - deaggregator
    networks:
      - portfolio-app
    build: .
    ports:
      - "127.0.0.1:5555:5555"
      
  price_producer:
    image: "abhishekcoder/securities_portfolio_app:price_producer"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
    networks:
      - portfolio-app
    restart: always

  deaggregator:
    image: "abhishekcoder/securities_portfolio_app:deaggregator"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
      - price_producer
    networks:
      - portfolio-app

  tnx_generator:
    image: "abhishekcoder/securities_portfolio_app:generator"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
    networks:
      - portfolio-app
    restart: always

  report:
    image: "abhishekcoder/securities_portfolio_app:report"
    env_file:
      - docker-compose-redis-variables.env
    depends_on:
      - redis
    networks:
      - portfolio-app
    restart: always

  redis:
    image: "redis/redis-stack:latest"
    env_file:
      - docker-compose-redis-variables.env
    command: /bin/sh -c "redis-stack-server --requirepass $$PASSWORD"
    ports:
      - "6379:6379"
    networks:
      - portfolio-app
    volumes:
      - redis_data:/data

volumes:
  redis_data: