spring:
  redis:
    host: localhost
    port: 6379
    password: admin
  main:
    allow-circular-references: true
    
price:
  update:
    stream: price_update_stream
    
timeseries:
  prefix: "price_history_ts:"
  bucket: 5
  stocks: HDFCBANK,TATAMOTORS

logging:
  level:
    org:
      springframework:
        web: DEBUG