apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-portfolio-app-server-deployment
  namespace: app-poc
  labels:
    app: securities-portfolio-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-portfolio-app-server
  template:
    metadata:
      labels:
        app: securities-portfolio-app-server
    spec:
      containers:
        - name: server
          image: abhishekcoder/securities_portfolio_app:server
          ports:
          - name: http
            containerPort: 5555
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: my-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-portfolio-app-price-producer-deployment
  namespace: app-poc
  labels:
    app: securities-portfolio-app-price-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-portfolio-app-price-producer
  template:
    metadata:
      labels:
        app: securities-portfolio-app-price-producer
    spec:
      containers:
        - name: price-producer
          image: abhishekcoder/securities_portfolio_app:price_producer
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: my-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-portfolio-app-deaggregator-deployment
  namespace: app-poc
  labels:
    app: securities-portfolio-app-deaggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-portfolio-app-deaggregator
  template:
    metadata:
      labels:
        app: securities-portfolio-app-deaggregator
    spec:
      containers:
        - name: deaggregator
          image: abhishekcoder/securities_portfolio_app:deaggregator
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: my-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-portfolio-app-generator-deployment
  namespace: app-poc
  labels:
    app: securities-portfolio-app-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-portfolio-app-generator
  template:
    metadata:
      labels:
        app: securities-portfolio-app-generator
    spec:
      containers:
        - name: generator
          image: abhishekcoder/securities_portfolio_app:generator
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: my-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securities-portfolio-app-report-deployment
  namespace: app-poc
  labels:
    app: securities-portfolio-app-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securities-portfolio-app-report
  template:
    metadata:
      labels:
        app: securities-portfolio-app-report
    spec:
      containers:
        - name: report
          image: abhishekcoder/securities_portfolio_app:report
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: my-config