spring:
  redis:
    host: localhost
    port: 6379
    password: Ay1ZwVVeVsHIHnPh0g9LyjQHsOHiqYgWqVsXSZQPAkw=
  main:
    allow-circular-references: true
    
price:
  update:
    stream: price_update_stream

logging:
  level:
    org:
      springframework:
        web: DEBUG